version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: subs
    ports:
      - "5433:5432"
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java_app
    depends_on:
      - postgres-db
    environment:
      DATABASE_URL: jdbc:postgresql://postgres-db/subs
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge